services:
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_arena_test
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: test
      DB_HOST: test-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sql_arena_test
      DB_PORT: 5432
      PORT: 3001
      JWT_SECRET: test_jwt_secret_key
    command: npm test
    depends_on:
      test-db:
        condition: service_healthy
    networks:
      - test-network

volumes:
  test_db_data:

networks:
  test-network:
    driver: bridge