name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          docker --version
          docker compose version

      - name: Run tests
        run: make test

      - name: Cleanup
        if: always()
        run: make test-clean || true